name: test

on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.TEST }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        
    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.TEST }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
