name: test

on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.TEST }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
